# Generated by Django 4.1.7 on 2023-03-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
